---
name: Documentation

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  documentation:
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@eb48d1b4b5da3058639e04491da5241ba931dae0 # v0
        with:
          docs-dependency-section: docs
          gh-pages-publish-directory: ./html/sleplet
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/sleplet
          pyproject-toml: ./pyproject.toml
          python-version: "3.13"
          template-directory: ./documentation
