---
name: Update Copyright

on:
  schedule:
    - cron: 0 3 1 1 *

jobs:
  update-licence-year:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@626ab242bf611add6f1b7af17aa24f8bf12c5521 # v0
        env:
          LICENCE_TOKEN: ${{ secrets.LICENCE_PAT }}
        with:
          licence-file: ./LICENCE.txt
          licence-token: ${{ env.LICENCE_TOKEN }}
