---
name: Update Copyright

on:
  schedule:
    - cron: 0 3 1 1 *

jobs:
  update-licence-year:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@a3d1207b08d8948851088b1f60c746aa2aa885f9 # v0
        with:
          licence-file: ./LICENCE.txt
          # yamllint disable-line rule:line-length
          licence-token: ${{ secrets.LICENCE_PAT }} # zizmor: ignore[secrets-outside-env]
