---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@dca9a13d483fe335f0b9edbd08494e6e4cd3b498 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml

      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/vale@dca9a13d483fe335f0b9edbd08494e6e4cd3b498 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
