---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@eb48d1b4b5da3058639e04491da5241ba931dae0 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml

      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/vale@eb48d1b4b5da3058639e04491da5241ba931dae0 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
